### ISSUE TITLE
Add NSHipster.es to iOS Dev Directory

### ISSUE THREAD

**Issue by mattt** [NSHipster/nshipster.es#5]
We should add NSHipster.es to [iOS Dev Directory](https://iosdevdirectory.com).

Because there aren't currently any Spanish language resources on this site, an entire new category must be added. I can't add this myself, because I don't know enough Spanish to write a title and description for that.

@jfsagasti When you have a chance, can you please make the necessary change to feed.json on our fork?

https://github.com/NSHipster/iOSDevDirectory

You should be able to copy-paste the French section and modify as needed. Let me know if you have any questions about the workflow!

**Comment by jfsagasti** [comment]
For sure! Thank you :)

**Comment by jfsagasti** [comment]
Hi @mattt! I've just sent the PR for the Spanish entry in the directory: https://github.com/daveverwer/iOSDevDirectory/pull/151

**Comment by mattt** [comment]
Perfect. Thanks, @jfsagasti! Looking forward to seeing the site updated with that change.
